// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Prattle
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_edit_sms_group = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_new_message = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_new_sms_group = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_sms_group = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_sms_group_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_sms_group_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sms_history = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_sms_history_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_sms_history_unselected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int contactName = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int menuCancelEdit = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int menuCreateGroup = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menuCreateMessage = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int menuSaveGroup = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int mobileNumber = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int selected = 2131165186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int contact_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int group_edit_bar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int main_action_bar = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
